name: build
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - run: cmake -S . -B build -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release
      - run: cmake --build build --config Release
        if: ${{ matrix.os == 'windows-2019' }}
      - run: cmake --build build
        if: ${{ matrix.os != 'windows-2019' }}
      - run: cmake --install build
      - name: archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-result-${{ matrix.os }}
          path: |
            install/
